name: CI Super Simples

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  teste:
    runs-on: ubuntu-latest
    steps:
      - name: Mensagem de teste
        run: echo "Workflow mínimo funcionando! ✅"
