name: CI Básico

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checar código
      uses: actions/checkout@v3

    - name: Exibir mensagem de teste
      run: echo "Workflow mínimo funcionando! ✅"
